# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: create .env file
      run: |
        echo "PORT=${{ secrets.PORT }}" > .env
        echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
        echo "CLOUD_NAME=${{ secrets.CLOUD_NAME }}" >> .env
        echo "CLOUD_KEY=${{ secrets.CLOUD_KEY }}" >> .env
        echo "CLOUD_SECRET=${{ secrets.CLOUD_SECRET }}" >> .env
        echo "EMAIL_NODEMAILER=${{ secrets.EMAIL_NODEMAILER }}" >> .env
        echo "PASSWORD_NODEMAILER=${{ secrets.PASSWORD_NODEMAILER }}" >> .env
        echo "PREFIX_ADMIN=${{ secrets.PREFIX_ADMIN }}" >> .env
        echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
        echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
        echo "ACCESS_TOKEN_LIFE=${{ secrets.ACCESS_TOKEN_LIFE }}" >> .env
        echo "REFRESH_TOKEN_LIFE=${{ secrets.REFRESH_TOKEN_LIFE }}" >> .env
        echo "SECRET_KEY_COOKIE=${{ secrets.SECRET_KEY_COOKIE }}" >> .env
    - run: pm2 restart furniture-web
